

# Project information
site_name: "Smarthome Doku"
site_url: "https://smarthome.ms1.de"
site_description: "Doku zu Home Assistant und sonstigen smarten Basteleien"
site_author: "saruter"
copyright: "Copyright 2019-2020 - saruter. Creative Commons Attribution 4.0."

# Repository
repo_name: "Github"
repo_url: "https://github.com/saruter/smarthome"
edit_uri: ""

#theme: 
#  name: "readthedocs"
#  custom_dir: "rtd-custom"
#theme: "rtd-mklab"
#theme: "rtd-dropdown"
#theme: "bootstrap"

## material theme
theme: 
  name: material
  language: de
  font: false 
#   text: roboto
#   code: Roboto Mono
  icon:
    logo: material/home
    favicon: img/favicon.png

  favicon: img/favicon.png
  palette:
    primary: blue
    accent: indigo
    #scheme: slate

  features: 
    - instant
    - tabs

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/saruter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/saruter
  

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true

  - toc:
      permalink: true

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
